#!/bin/bash

# Change to the repo directory
cd ${OPENSHIFT_REPO_DIR}

# Start our Celery workers
celery multi restart worker1 \
    --pidfile="${OPENSHIFT_DATA_DIR}%n.pid" \
    --logfile="$OPENSHIFT_LOG_DIR%n.log" \
    --app=dailienator.celery \
    --loglevel=info