#!/bin/bash

source ${OPENSHIFT_HOMEDIR}python/virtenv/bin/activate
 
export PYTHON_EGG_CACHE=${OPENSHIFT_HOME_DIR}python/virtenv/lib/python2.7/site-packages/

echo "Preparing the openshift_settings.py file for use"
cp "$OPENSHIFT_REPO_DIR"dailienator/config/openshift_settings.py "$OPENSHIFT_REPO_DIR"dailienator/config/settings.py
 
echo "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"manage.py syncdb --noinput

echo "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py migrate'"
python "$OPENSHIFT_REPO_DIR"manage.py migrate

echo "Creating wsgi directory at '${OPENSHIFT_REPO_DIR}'"
mkdir -p "$OPENSHIFT_REPO_DIR"wsgi/static
mkdir -p "$OPENSHIFT_REPO_DIR"wsgi/media

echo "Adding .htaccess to '${OPENSHIFT_REPO_DIR}wsgi'"
cp ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/htaccess ${OPENSHIFT_REPO_DIR}wsgi/.htaccess
 
echo "Executing 'python ${OPENSHIFT_REPO_DIR}manage.py collectstatic --noinput -v0'"
python "$OPENSHIFT_REPO_DIR"manage.py collectstatic --noinput -v0
